name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 8,21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
	# clone该仓库到工作流中
      - name: 'Checkout codes'
        uses: actions/checkout@v1
	# 执行仓库中的脚本文件
      - name: 'Get Weather'
        run: bash ./weather.sh
	# 获取格式化的日期并存入GitHub内置的环境变量中
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
	# 发送邮件
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
	  # sectret的环境变量需要配置在setting中的secret下
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Guangzhou Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: ihzur@qq.com
          from: GitHub Actions
          content_type: text/html
